export const BASS_ERROR_UNKNOWN = -1;
export const BASS_OK = 0;
export const BASS_ERROR_MEM = 1;
export const BASS_ERROR_FILEOPEN = 2;
export const BASS_ERROR_DRIVER = 3;
export const BASS_ERROR_BUFLOST = 4;
export const BASS_ERROR_HANDLE = 5;
export const BASS_ERROR_FORMAT = 6;
export const BASS_ERROR_POSITION = 7;
export const BASS_ERROR_INIT = 8;
export const BASS_ERROR_START = 9;
export const BASS_ERROR_SSL = 10;
export const BASS_ERROR_REINIT = 11;
export const BASS_ERROR_ALREADY = 14;
export const BASS_ERROR_NOTAUDIO = 17;
export const BASS_ERROR_NOCHAN = 18;
export const BASS_ERROR_ILLTYPE = 19;
export const BASS_ERROR_ILLPARAM = 20;
export const BASS_ERROR_NO3D = 21;
export const BASS_ERROR_NOEAX = 22;
export const BASS_ERROR_DEVICE = 23;
export const BASS_ERROR_NOPLAY = 24;
export const BASS_ERROR_FREQ = 25;
export const BASS_ERROR_NOTFILE = 27;
export const BASS_ERROR_NOHW = 29;
export const BASS_ERROR_EMPTY = 31;
export const BASS_ERROR_NONET = 32;
export const BASS_ERROR_CREATE = 33;
export const BASS_ERROR_NOFX = 34;
export const BASS_ERROR_NOTAVAIL = 37;
export const BASS_ERROR_DECODE = 38;
export const BASS_ERROR_DX = 39;
export const BASS_ERROR_TIMEOUT = 40;
export const BASS_ERROR_FILEFORM = 41;
export const BASS_ERROR_SPEAKER = 42;
export const BASS_ERROR_VERSION = 43;
export const BASS_ERROR_CODEC = 44;
export const BASS_ERROR_ENDED = 45;
export const BASS_ERROR_BUSY = 46;
export const BASS_ERROR_UNSTREAMABLE = 47;
export const BASS_ERROR_PROTOCOL = 48;
export const BASS_ERROR_DENIED = 49;

// Hashmap, mapping error codes to string representations
export const ERROR_MAP: Map<number, string> = new Map([
  [BASS_ERROR_UNKNOWN, "BASS_ERROR_UNKNOWN"],
  [BASS_OK, "BASS_OK"],
  [BASS_ERROR_MEM, "BASS_ERROR_MEM"],
  [BASS_ERROR_FILEOPEN, "BASS_ERROR_FILEOPEN"],
  [BASS_ERROR_DRIVER, "BASS_ERROR_DRIVER"],
  [BASS_ERROR_BUFLOST, "BASS_ERROR_BUFLOST"],
  [BASS_ERROR_HANDLE, "BASS_ERROR_HANDLE"],
  [BASS_ERROR_FORMAT, "BASS_ERROR_FORMAT"],
  [BASS_ERROR_POSITION, "BASS_ERROR_POSITION"],
  [BASS_ERROR_INIT, "BASS_ERROR_INIT"],
  [BASS_ERROR_START, "BASS_ERROR_START"],
  [BASS_ERROR_SSL, "BASS_ERROR_SSL"],
  [BASS_ERROR_REINIT, "BASS_ERROR_REINIT"],
  [BASS_ERROR_ALREADY, "BASS_ERROR_ALREADY"],
  [BASS_ERROR_NOTAUDIO, "BASS_ERROR_NOTAUDIO"],
  [BASS_ERROR_NOCHAN, "BASS_ERROR_NOCHAN"],
  [BASS_ERROR_ILLTYPE, "BASS_ERROR_ILLTYPE"],
  [BASS_ERROR_ILLPARAM, "BASS_ERROR_ILLPARAM"],
  [BASS_ERROR_NO3D, "BASS_ERROR_NO3D"],
  [BASS_ERROR_NOEAX, "BASS_ERROR_NOEAX"],
  [BASS_ERROR_DEVICE, "BASS_ERROR_DEVICE"],
  [BASS_ERROR_NOPLAY, "BASS_ERROR_NOPLAY"],
  [BASS_ERROR_FREQ, "BASS_ERROR_FREQ"],
  [BASS_ERROR_NOTFILE, "BASS_ERROR_NOTFILE"],
  [BASS_ERROR_NOHW, "BASS_ERROR_NOHW"],
  [BASS_ERROR_EMPTY, "BASS_ERROR_EMPTY"],
  [BASS_ERROR_NONET, "BASS_ERROR_NONET"],
  [BASS_ERROR_CREATE, "BASS_ERROR_CREATE"],
  [BASS_ERROR_NOFX, "BASS_ERROR_NOFX"],
  [BASS_ERROR_NOTAVAIL, "BASS_ERROR_NOTAVAIL"],
  [BASS_ERROR_DECODE, "BASS_ERROR_DECODE"],
  [BASS_ERROR_DX, "BASS_ERROR_DX"],
  [BASS_ERROR_TIMEOUT, "BASS_ERROR_TIMEOUT"],
  [BASS_ERROR_FILEFORM, "BASS_ERROR_FILEFORM"],
  [BASS_ERROR_SPEAKER, "BASS_ERROR_SPEAKER"],
  [BASS_ERROR_VERSION, "BASS_ERROR_VERSION"],
  [BASS_ERROR_CODEC, "BASS_ERROR_CODEC"],
  [BASS_ERROR_ENDED, "BASS_ERROR_ENDED"],
  [BASS_ERROR_BUSY, "BASS_ERROR_BUSY"],
  [BASS_ERROR_UNSTREAMABLE, "BASS_ERROR_UNSTREAMABLE"],
  [BASS_ERROR_PROTOCOL, "BASS_ERROR_PROTOCOL"],
  [BASS_ERROR_DENIED, "BASS_ERROR_DENIED"],
]);
