// BASS_ChannelGetTags tags
export const BASS_TAG_ID3 = 0; // ID3v1 tags : TAG_ID3 structure
export const BASS_TAG_ID3V2 = 1; // ID3v2 tags : variable length block
export const BASS_TAG_OGG = 2; // OGG comments : series of null-terminated UTF-8 strings
export const BASS_TAG_HTTP = 3; // HTTP headers : series of null-terminated ASCII strings
export const BASS_TAG_ICY = 4; // ICY headers : series of null-terminated ANSI strings
export const BASS_TAG_META = 5; // ICY metadata : ANSI string
export const BASS_TAG_APE = 6; // APE tags : series of null-terminated UTF-8 strings
export const BASS_TAG_MP4 = 7; // MP4/iTunes metadata : series of null-terminated UTF-8 strings
export const BASS_TAG_WMA = 8; // WMA tags : series of null-terminated UTF-8 strings
export const BASS_TAG_VENDOR = 9; // OGG encoder : UTF-8 string
export const BASS_TAG_LYRICS3 = 10; // Lyric3v2 tag : ASCII string
export const BASS_TAG_CA_CODEC = 11; // CoreAudio codec info : TAG_CA_CODEC structure
export const BASS_TAG_MF = 13; // Media Foundation tags : series of null-terminated UTF-8 strings
export const BASS_TAG_WAVEFORMAT = 14; // WAVE format : WAVEFORMATEEX structure
export const BASS_TAG_AM_NAME = 16; // Android Media codec name : ASCII string
export const BASS_TAG_ID3V2_2 = 17; // ID3v2 tags (2nd block) : variable length block
export const BASS_TAG_AM_MIME = 18; // Android Media MIME type : ASCII string
export const BASS_TAG_LOCATION = 19; // redirected URL : ASCII string
export const BASS_TAG_RIFF_INFO = 0x100; // RIFF "INFO" tags : series of null-terminated ANSI strings
export const BASS_TAG_RIFF_BEXT = 0x101; // RIFF/BWF "bext" tags : TAG_BEXT structure
export const BASS_TAG_RIFF_CART = 0x102; // RIFF/BWF "cart" tags : TAG_CART structure
export const BASS_TAG_RIFF_DISP = 0x103; // RIFF "DISP" text tag : ANSI string
export const BASS_TAG_RIFF_CUE = 0x104; // RIFF "cue " chunk : TAG_CUE structure
export const BASS_TAG_RIFF_SMPL = 0x105; // RIFF "smpl" chunk : TAG_SMPL structure
export const BASS_TAG_APE_BINARY = 0x1000; // + index #, binary APE tag : TAG_APE_BINARY structure
export const BASS_TAG_MUSIC_NAME = 0x10000; // MOD music name : ANSI string
export const BASS_TAG_MUSIC_MESSAGE = 0x10001; // MOD message : ANSI string
export const BASS_TAG_MUSIC_ORDERS = 0x10002; // MOD order list : BYTE array of pattern numbers
export const BASS_TAG_MUSIC_AUTH = 0x10003; // MOD author : UTF-8 string
export const BASS_TAG_MUSIC_INST = 0x10100; // + instrument #, MOD instrument name : ANSI string
export const BASS_TAG_MUSIC_CHAN = 0x10200; // + channel #, MOD channel name : ANSI string
export const BASS_TAG_MUSIC_SAMPLE = 0x10300; // + sample #, MOD sample name : ANSI string
